import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider, auth } from "@clerk/nextjs";

import "../globals.css";
import ModalProvider from "@/components/providers/ModalProvider";
import { ToastProvider } from "@/components/providers/ToastProvider";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId } = auth();

  if (!userId) {
    redirect("/sign-in");
  }

  const store = await prisma.store.findFirst({
    where: { userId },
  });

  if (store) {
    redirect(`/${store.id}`);
  }
  return (
    <ClerkProvider>
      <html lang="en">
        <ToastProvider />
        <ModalProvider />
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
